#!/usr/bin/env python3
import base64
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import subprocess

# Setup auth if KUBE64 is set
if os.environ.get("KUBE64"):
  Path("kube-config.yaml").write_bytes(base64.b64decode(os.environ["KUBE64"]))
  os.environ["KUBECONFIG"] = "kube-config.yaml"

OUTPUT_FILE = os.environ.get(
    "OUTPUT_FILE", str(Path(__file__).parent / "config.yaml")
)
CHECK_INTERVAL = os.environ.get("CHECK_INTERVAL", "5m")
CERT_THRESHOLD = os.environ.get("CERTIFICATE_EXPIRATION_THRESHOLD", "48h")

CONTEXTS = [
    "cedille-k8s-cedille-sandbox-gatus",
    "cedille-k8s-shared-gatus",
    "cedille-k8s-cedille-production-v2-gatus",
]


def get_json(cmd):
  res = subprocess.run(cmd, capture_output=True, text=True)
  return json.loads(res.stdout).get("items", []) if res.returncode == 0 else []


def sanitize(name):
  return re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-")


def get_group(host):
  if "etsmtl.club" in host:
    return "shared"
  if "staging" in host or "dev" in host:
    return "staging"
  if "internal" in host or "admin" in host:
    return "internal"
  return "production"


print("Discovering endpoints across clusters...")
seen = set()
endpoints = []

for ctx in CONTEXTS:
  # Check context exists
  if (
      subprocess.run(
          ["kubectl", "config", "get-contexts", ctx], capture_output=True
      ).returncode
      != 0
  ):
    print(f"Warning: Context {ctx} not found, skipping...")
    continue

  # Fetch both HTTPProxy and Ingress in a single kubectl call
  items = get_json([
      "kubectl",
      "--context",
      ctx,
      "get",
      "httpproxies.projectcontour.io,ingress",
      "-A",
      "-o",
      "json",
  ])

  for item in items:
    kind = item.get("kind")
    spec = item.get("spec", {})
    meta = item.get("metadata", {})
    ann = meta.get("annotations") or {}

    if ann.get("gatus.cedille/skip-monitor") == "true":
      continue
    if spec.get("ingressClassName") not in (None, "contour"):
      continue

    # Extract candidates
    entries = []
    if kind == "HTTPProxy":
      host = spec.get("virtualhost", {}).get("fqdn")
      path = ann.get("gatus.cedille/health-path") or "/"
      if host:
        entries.append((host, path))
    elif kind == "Ingress":
      if meta.get("name", "").startswith("cm-acme-http-solver"):
        continue
      for rule in spec.get("rules", []):
        host = rule.get("host")
        path = ann.get("gatus.cedille/health-path") or "/"
        if host:
          entries.append((host, path))

    # Process and filter endpoints
    for host, path in entries:
      if not host or "*" in host or host.endswith(".local") or "minikube" in host:
        continue
      if "acme-challenge" in path or ".well-known" in path:
        continue

      name = sanitize(host)
      if name in seen:
        print(f"Ignored duplicate endpoint: {name} ({host})")
        continue
      seen.add(name)

      proto = ann.get("gatus.cedille/protocol", "https")
      path = f"/{path.lstrip('/')}"

      if proto == "tcp":
        endpoints.append(
            f"  - name: {name}\n"
            f"    group: {get_group(host)}\n"
            f'    url: "tcp://{host.rstrip("/")}"\n'
            f"    interval: {CHECK_INTERVAL}\n"
            "    conditions:\n"
            '      - "[CONNECTED] == true"\n'
        )
      else:
        endpoints.append(
            f"  - name: {name}\n"
            f"    group: {get_group(host)}\n"
            f'    url: "{proto}://{host}{path}"\n'
            f"    interval: {CHECK_INTERVAL}\n"
            "    conditions:\n"
            '      - "[STATUS] == 200"\n'
            f'      - "[CERTIFICATE_EXPIRATION] > {CERT_THRESHOLD}"\n'
        )

# Build configuration file
date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
header = f"""# Auto-generated Gatus configuration
# Generated at: {date_str}
# Do not edit manually - this file is automatically generated
metrics: true
skip-invalid-config-update: true

storage:
  type: sqlite
  path: /data/gatus.db

alerting:
  discord:
    enabled: true
    webhook-url: "${{DISCORD_WEBHOOK_URL}}"

web:
  port: 8080

endpoints:
"""

Path(OUTPUT_FILE).write_text(header + "\n".join(endpoints))
print(f"Generated configuration file: {OUTPUT_FILE}")
print(f"Total endpoints configured: {len(endpoints)}")
print("Configuration generation complete!")
