#!/usr/bin/env bash
set -euo pipefail

# Setup auth
if [ $(kubectl config get-clusters | wc -l) -eq 1 ]; then
    echo "$KUBE64" | base64 -d > kube-config.yaml
    export KUBECONFIG=kube-config.yaml
fi

# Configuration
OUTPUT_FILE="${OUTPUT_FILE:-config.yaml}"
CHECK_INTERVAL="${CHECK_INTERVAL:-5m}"
CERTIFICATE_EXPIRATION_THRESHOLD="${CERTIFICATE_EXPIRATION_THRESHOLD:-48h}"

# Kubernetes contexts to scan
CONTEXTS=(
cedille-k8s-cedille-sandbox-gatus
cedille-k8s-shared-gatus
cedille-k8s-cedille-production-v2-gatus
)

# Temporary file to store all discovered endpoints
TEMP_ENDPOINTS=$(mktemp)

echo "🔍 Discovering endpoints across clusters..."

# Discover endpoints from all clusters
for ctx in "${CONTEXTS[@]}"; do
  # Check if context exists
  if ! kubectl config get-contexts "$ctx" &>/dev/null; then
    echo "Warning: Context $ctx not found, skipping..."
    continue
  fi

  # Get HTTPProxy endpoints and prefer gatus annotations when present
  kubectl --context="$ctx" get httpproxies.projectcontour.io -A -o json 2>/dev/null \
    | jq -r '.items[]
    | select(.spec.ingressClassName == null or .spec.ingressClassName == "contour")
    | . as $item
    | ($item.spec.virtualhost.fqdn // "") as $fqdn
    | ($item.metadata.annotations["gatus.cedille/health-path"] // ($item.spec.routes[0].conditions[0].prefix // "/")) as $path
    | ($item.metadata.annotations["gatus.cedille/protocol"] // "https") as $proto
    | ($item.metadata.annotations["gatus.cedille/skip-monitor"] // "false") as $skip
    | $fqdn + "|" + ($path|tostring) + "|" + $proto + "|" + ($skip|tostring)' >> "$TEMP_ENDPOINTS" || true

  # Get Ingress endpoints and prefer gatus annotations when present
  kubectl --context="$ctx" get ingress -A -o json 2>/dev/null \
    | jq -r '.items[]
    | select(.spec.ingressClassName == null or .spec.ingressClassName == "contour")
    | . as $item
    | ($item.spec.rules[]? | .host) as $host
    | ($item.metadata.annotations["gatus.cedille/health-path"] // ($item.spec.rules[0].http.paths[0].path // "/")) as $path
    | ($item.metadata.annotations["gatus.cedille/protocol"] // "https") as $proto
    | ($item.metadata.annotations["gatus.cedille/skip-monitor"] // "false") as $skip
    | ($host // "") + "|" + ($path|tostring) + "|" + $proto + "|" + ($skip|tostring)' >> "$TEMP_ENDPOINTS" || true
done

# Remove duplicates and sort
UNIQUE_ENDPOINTS=$(sort -u "$TEMP_ENDPOINTS")
ENDPOINT_COUNT=$(echo "$UNIQUE_ENDPOINTS" | grep -v '^$' | wc -l)

echo "Found $ENDPOINT_COUNT unique endpoints"

# Generate Gatus config.yaml
cat > "$OUTPUT_FILE" <<'EOF'
# Auto-generated Gatus configuration
# Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Do not edit manually - this file is automatically generated
metrics: true

storage:
  type: sqlite
  path: /data/gatus.db

alerting:
  discord:
    enabled: true
    webhook-url: "https://discord.com/api/webhooks/1523550041023709316/BegnppsG4eohO5Huai-SC2krnOW1hWBNf68IH73FAUvLzOdRT9OeT0et47_oCr-KO9Rh"

# Web UI configuration
web:
  port: 8080

# Endpoints to monitor
endpoints:
EOF

# Add each endpoint to the config
while IFS= read -r endpoint; do
  # Skip empty lines
  [[ -z "$endpoint" ]] && continue

  # Each discovered line is stored as: host|path|protocol|skip
  HOST=$(echo "$endpoint" | cut -d '|' -f1)
  PATH_VAL=$(echo "$endpoint" | cut -d '|' -f2)
  PROTO=$(echo "$endpoint" | cut -d '|' -f3)
  SKIP=$(echo "$endpoint" | cut -d '|' -f4)

  # Sanitize endpoint name (replace dots and hyphens for Gatus compatibility)
  ENDPOINT_NAME=$(echo "$HOST" | sed 's/\./-/g')

  # Determine group based on domain patterns
  GROUP="production"
  if [[ "$endpoint" == *"etsmtl.club"* ]]; then
      GROUP="shared"
  elif [[ "$endpoint" == *"staging"* ]] || [[ "$endpoint" == *"dev"* ]]; then
      GROUP="staging"
  elif [[ "$endpoint" == *"internal"* ]] || [[ "$endpoint" == *"admin"* ]]; then
      GROUP="internal"
  fi

  # Respect explicit skip annotation
  if [[ "$SKIP" == "true" ]]; then
    continue
  fi

  # Skip obvious local-only hosts unless explicitly requested
  if [[ "$HOST" == *".local"* ]] || [[ "$HOST" == *"minikube"* ]] || [[ "$HOST" == "" ]] ; then
    continue
  fi

  # Default protocol/path if empty
  PROTO=${PROTO:-https}
  PATH_VAL=${PATH_VAL:-/}

  # Add endpoint configuration using discovered path/protocol and a permissive status range (2xx-3xx)
  cat >> "$OUTPUT_FILE" <<EOF
  - name: ${ENDPOINT_NAME}
    group: ${GROUP}
    url: "${PROTO}://${HOST}${PATH_VAL}"
    interval: ${CHECK_INTERVAL}
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION_THRESHOLD}"

EOF
done <<< "$UNIQUE_ENDPOINTS"

# Clean up
rm -f "$TEMP_ENDPOINTS"

echo "Generated configuration file: $OUTPUT_FILE"
echo "Total endpoints configured: $ENDPOINT_COUNT"

# Validate the generated YAML (optional, requires yq)
if command -v yq &> /dev/null; then
  echo "✓ Validating YAML syntax..."
  yq eval '.' "$OUTPUT_FILE" > /dev/null && echo "✓ YAML is valid"
fi

echo "Configuration generation complete!"
