#!/usr/bin/env bash
set -euo pipefail

# Configuration
OUTPUT_FILE="${OUTPUT_FILE:-config.yaml}"
CHECK_INTERVAL="${CHECK_INTERVAL:-5m}"
CERTIFICATE_EXPIRATION_THRESHOLD="${CERTIFICATE_EXPIRATION_THRESHOLD:-48h}"

# Kubernetes contexts to scan
CONTEXTS=(
  cedille-k8s-shared
  cedille-k8s-cedille-production-v2
)

# Temporary file to store all discovered endpoints
TEMP_ENDPOINTS=$(mktemp)

echo "🔍 Discovering endpoints across clusters..."

# Discover endpoints from all clusters
for ctx in "${CONTEXTS[@]}"; do
  # Check if context exists
  if ! kubectl config get-contexts "$ctx" &>/dev/null; then
    echo "Warning: Context $ctx not found, skipping..."
    continue
  fi

  # Get HTTPProxy endpoints
  kubectl --context="$ctx" get httpproxies.projectcontour.io -A -o json 2>/dev/null \
    | jq -r '.items[]
    | select(.spec.ingressClassName == null or .spec.ingressClassName == "contour")
    | .spec.virtualhost.fqdn' >> "$TEMP_ENDPOINTS" || true

  # Get Ingress endpoints
  kubectl --context="$ctx" get ingress -A -o json 2>/dev/null \
    | jq -r '.items[]
    | select(.spec.ingressClassName == null or .spec.ingressClassName == "contour")
    | .spec.rules[].host' >> "$TEMP_ENDPOINTS" || true
done

# Remove duplicates and sort
UNIQUE_ENDPOINTS=$(sort -u "$TEMP_ENDPOINTS")
ENDPOINT_COUNT=$(echo "$UNIQUE_ENDPOINTS" | grep -v '^$' | wc -l)

echo "Found $ENDPOINT_COUNT unique endpoints"

# Generate Gatus config.yaml
cat > "$OUTPUT_FILE" <<'EOF'
# Auto-generated Gatus configuration
# Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Do not edit manually - this file is automatically generated

storage:
  type: sqlite
  path: /data/gatus.db

# Web UI configuration
web:
  port: 8080

# Endpoints to monitor
endpoints:
EOF

# Add each endpoint to the config
while IFS= read -r endpoint; do
  # Skip empty lines
  [[ -z "$endpoint" ]] && continue

  # Sanitize endpoint name (replace dots and hyphens for Gatus compatibility)
  ENDPOINT_NAME=$(echo "$endpoint" | sed 's/\./-/g')

  # Determine group based on domain patterns
  GROUP="production"
  if [[ "$endpoint" == *"staging"* ]] || [[ "$endpoint" == *"dev"* ]]; then
    GROUP="staging"
  elif [[ "$endpoint" == *"internal"* ]] || [[ "$endpoint" == *"admin"* ]]; then
    GROUP="internal"
  fi

  # Add endpoint configuration
  cat >> "$OUTPUT_FILE" <<EOF
  - name: ${ENDPOINT_NAME}
    group: ${GROUP}
    url: "https://${endpoint}/"
    interval: ${CHECK_INTERVAL}
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION_THRESHOLD}"
    alerts:
      - type: slack
        enabled: false
        failure-threshold: 3
        success-threshold: 2

EOF
done <<< "$UNIQUE_ENDPOINTS"

# Clean up
rm -f "$TEMP_ENDPOINTS"

echo "Generated configuration file: $OUTPUT_FILE"
echo "Total endpoints configured: $ENDPOINT_COUNT"

# Validate the generated YAML (optional, requires yq)
if command -v yq &> /dev/null; then
  echo "✓ Validating YAML syntax..."
  yq eval '.' "$OUTPUT_FILE" > /dev/null && echo "✓ YAML is valid"
fi

echo "Configuration generation complete!"
