name: Deploy Gatus App

on:
  push:
    branches: ["main"]
    paths:
      - 'config.yaml'
      - 'Dockerfile'
      - '.github/workflows/deploy-vm.yml'
      - "generate-gatus-config.sh"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT}}

      
      - name: Redéployer Gatus
        run: |
          gcloud compute ssh ${{ secrets.GCP_MACHINE_NAME }} \
            --zone="${{ secrets.REGION }}" \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --command="
              cd gatus
              GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no' git pull origin main
              chmod +x generate-gatus-config.sh
              ./generate-gatus-config.sh
              docker restart gatus
            "